[tool.poetry]
name = "astrologu backend"
version = "0.1.0"
description = ""
authors = ["Adrian Makridenko"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
flask = "^2.0.1"
flask-login = "^0.6.2"
flask-openid = "^1.3.0"
flask-mail = "^0.9.1"
sqlalchemy = "^2.0.20"
flask-sqlalchemy = "^3.0.5"
sqlalchemy-migrate = "^0.13.0"
flask-whooshalchemy = "^0.56"
flask-wtf = "^1.1.1"
pytz = "^2022.7"
flask-babel = "^3.1.0"
flup = "^1.0.3"
kerykeion = "^4.0.5"
flask-script = "^2.0.6"
pytest = "^7.0.1"
pytest-flask = "^1.2.0"
swisseph = "^0.0.0.dev1"
ephem = "^4.1.4"
geopy = "^2.3.0"
astrology = "^0.0.1.dev0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
