[tool.poetry]
name = "astrologu backend"
version = "0.1.0"
description = ""
authors = ["Adrian Makridenko"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
flask = "2.0.1"
geopy = "2.2.0,"
ephem = "4.0.0.2"
jinja2 = "3.0.1,"
flask-testing = "0.8.1"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
